### ISSUE TITLE
No need to wait after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [FABtotum/FABlin#17]
In the file "FABlin/Marlin/Marlin_main.cpp", in the function "I2C_read()" there is a timeout with millis() after the Wire.requestFrom(). However, there is nothing to wait for.
Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

Since the return value of Wire.endTransmission() is not tested, the test for Wire.requestFrom() could perhaps be omitted as well:
```
  Wire.requestFrom(SERIAL_ID_ADDR, 1);    // request 1 bytes from slave device SERIAL_ID_ADDR
  return( (char) Wire.read());      // return a byte as character
}
```

When the Wire.requestFrom() needs a check for a valid I2C transaction, it could be like this:
```
  Wire.requestFrom(SERIAL_ID_ADDR, 1);    // request 1 bytes from slave device SERIAL_ID_ADDR
  if(Wire.available() != 1)       // request for 1 bytes failed ?
  {
    return('?');      // return a byte as character
  }
  else
  {
    return( (char) Wire.read());      // return a byte as character
  }
}
```

**Comment by simone-fabteam** [comment]
Thanks for your suggestion. That part of the codebase is ancient to say the least, and almost unused nowadays (although required for older FABtotum heads) so it was never really called into question either.

I'm putting this into development for a future revision of the firmware.

**Comment by simone-fabteam** [comment]
Changed in: https://github.com/FABtotum/FABlin/commit/80f0b1c093edc48651150f3fe9da73d027bcb0a3. Need to be tested before release.
